# Application Name
spring.application.name=music-catalog-insights

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-gentle-heart-axnk0x27-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8Ewz7OfoBihx

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081